steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ai_service:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ai_service:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run',
        'deploy',
        'ai-service',
        '--image',
        'gcr.io/$PROJECT_ID/ai_service:$COMMIT_SHA',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--set-env-vars',
        'DATABASE_URL=$DATABASE_URL,AZURE_TENANT=$AZURE_TENANT,AZURE_CLIENT_ID=$AZURE_CLIENT_ID,API_AUDIENCE=$API_AUDIENCE,JWKS_URL=$JWKS_URL,LOG_LEVEL=$LOG_LEVEL,CORS_ORIGINS=$CORS_ORIGINS',
      ]
images:
  - 'gcr.io/$PROJECT_ID/ai_service:$COMMIT_SHA'
